# C:\Users\potyk\Downloads\flutter_windows_v1.12.13+hotfix.5-stable\flutter\bin\flutter.bat pub pub run build_runner build
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
          any_map: true